version: '3'

tasks:
  build:
    cmds:
      - rm -rf build
      - mkdir -p build
      - javac --release 17 -encoding UTF-8 -d build src/Main.java
    silent: true

  jar:
    deps: [build]
    cmds:
      - jar -c -f build/lab1.jar -e Main -C build .
    silent: true

  run:
    deps: [jar]
    cmds:
      - java -jar build/lab1.jar
    silent: true