version: '3'

tasks:
  build:
    cmds:
      - rm -rf build
      - mkdir -p build
      - javac --release 17 -encoding UTF-8 -cp lib/Pokemon.jar -d build src/Main.java src/pokemons/**/*.java src/moves/**/*.java
    silent: true

  jar:
    deps: [build]
    cmds:
      - jar -c -f build/lab2.jar -e Main -C build .
    silent: true

  run:
    deps: [jar]
    cmds:
      - java -cp lib/Pokemon.jar:build/lab2.jar Main
    silent: true
